import type { Scheme, Rule } from '@/types';
const rule = (
  field: Rule['field'],
  operator: Rule['operator'],
  value: Rule['value'],
  label: string,
  required = true,
  weight = 15,
): Rule => ({ id: field, field, operator, value, label, required, weight });
const definitions = [
  [
    'machinery',
    'Machinery modernisation',
    'Manufacturing,Engineering',
    'Machinery purchase,Technology upgrade',
    'Subsidy',
    'Central',
    'All',
    2500000,
    'Illustrative capital support for equipment upgrades.',
  ],
  [
    'digital',
    'Digital tools for small businesses',
    'IT/software,Services,Retail,Trading,Manufacturing,Engineering',
    'Digitalisation,Technology upgrade',
    'Reimbursement',
    'Central',
    'All',
    300000,
    'Illustrative reimbursement for eligible software and digital adoption.',
  ],
  [
    'export',
    'Export market access',
    'Manufacturing,Engineering,Trading,Services,IT/software,Food processing,Agriculture-related',
    'Export,Market expansion',
    'Reimbursement',
    'Central',
    'All',
    1000000,
    'Illustrative support for trade fairs and access to overseas markets.',
  ],
  [
    'working-capital',
    'Small business working capital',
    'Manufacturing,Engineering,Trading,Retail,IT/software,Services,Food processing,Agriculture-related',
    'Working capital',
    'Loan',
    'Central',
    'All',
    5000000,
    'Illustrative credit support to meet day-to-day business needs.',
  ],
  [
    'women',
    'Women-led enterprise growth',
    'Manufacturing,Engineering,Trading,Retail,IT/software,Services,Startups,Food processing,Agriculture-related',
    'Women entrepreneurship,Market expansion',
    'Loan',
    'Central',
    'All',
    2000000,
    'Illustrative growth finance for women-owned enterprises.',
  ],
  [
    'startup',
    'Early-stage innovation',
    'Startups,IT/software,Engineering',
    'Startup funding,Research & development',
    'Grant',
    'Central',
    'All',
    2000000,
    'Illustrative early-stage funding for developing and validating innovative products.',
  ],
  [
    'green',
    'Cleaner energy transition',
    'Manufacturing,Engineering,Services,Retail,Food processing,Agriculture-related',
    'Green energy,Renewable energy',
    'Subsidy',
    'State',
    'Maharashtra',
    1500000,
    'Illustrative assistance for energy-efficiency improvements.',
  ],
  [
    'food',
    'Food processing capacity',
    'Food processing,Agriculture-related',
    'Machinery purchase,Infrastructure,Market expansion',
    'Subsidy',
    'State',
    'Maharashtra',
    1000000,
    'Illustrative assistance to strengthen processing, packaging, and storage.',
  ],
  [
    'quality',
    'Quality certification support',
    'Manufacturing,Engineering,IT/software,Services,Food processing',
    'Quality certification,Market expansion',
    'Reimbursement',
    'Central',
    'All',
    200000,
    'Illustrative reimbursement for eligible quality certification expenses.',
  ],
  [
    'skills',
    'Workforce skills development',
    'Manufacturing,Engineering,Services,IT/software,Retail,Trading',
    'Skill development,Employment generation',
    'Grant',
    'State',
    'Karnataka',
    500000,
    'Illustrative training assistance for employees of small businesses.',
  ],
  [
    'retail',
    'Retail business expansion',
    'Retail,Trading',
    'Market expansion,Infrastructure,Digitalisation',
    'Loan',
    'State',
    'Gujarat',
    1000000,
    'Illustrative credit assistance for retail infrastructure and expansion.',
  ],
  [
    'innovation',
    'Technology and product development',
    'Engineering,IT/software,Manufacturing,Startups',
    'Research & development,Technology upgrade',
    'Grant',
    'State',
    'Tamil Nadu',
    2500000,
    'Illustrative assistance for research and product development.',
  ],
  [
    'services',
    'Service enterprise growth',
    'Services,IT/software',
    'Market expansion,Employment generation,Infrastructure',
    'Loan',
    'Central',
    'All',
    1500000,
    'Illustrative business development support for service enterprises.',
  ],
  [
    'agri',
    'Agri-business value addition',
    'Agriculture-related,Food processing',
    'Machinery purchase,Infrastructure,Green energy',
    'Grant',
    'Central',
    'All',
    1800000,
    'Illustrative support for agriculture-related processing and value addition.',
  ],
] as const;
export const seedSchemes: Scheme[] = definitions.map(
  ([
    id,
    title,
    sectors,
    goals,
    funding,
    level,
    state,
    maximumBenefit,
    description,
  ]) => ({
    id: 'demo-' + id,
    name: title + ' — Demo',
    description,
    detail:
      description +
      ' This is an illustrative product-testing record, not a named government scheme. Its conditions, amounts, and dates are examples only. Replace it with reviewed official records before offering application guidance.',
    level,
    ministry: 'Illustrative administering authority',
    department: 'Demo MSME support programme',
    state,
    industries: sectors.split(','),
    categories: goals.split(','),
    fundingType: funding,
    benefit:
      'Illustrative support up to INR ' +
      maximumBenefit.toLocaleString('en-IN'),
    maximumBenefit,
    subsidyPercentage: funding === 'Subsidy' ? 20 : null,
    loanSupport: funding === 'Loan',
    grantSupport: funding === 'Grant',
    reimbursement: funding === 'Reimbursement',
    rules: [
      rule('industry', 'in', sectors.split(','), 'Supported business sector'),
      ...(state === 'All'
        ? []
        : [rule('state', 'in', [state], state + ' business location')]),
      rule(
        'turnover',
        'range',
        [0, 100000000],
        'Annual turnover within illustrative INR 10 crore limit',
      ),
      rule(
        'investment',
        'range',
        [0, 50000000],
        'Investment within illustrative INR 5 crore limit',
      ),
      rule('employees', 'range', [0, 500], 'Up to 500 employees'),
      rule(
        'registrations',
        'all',
        ['Udyam Registration', 'PAN'],
        'Udyam registration and PAN',
      ),
      rule(
        'objectives',
        'any',
        goals.split(','),
        'A matching business objective',
        false,
        25,
      ),
      ...(id === 'women'
        ? [
            rule(
              'womenOwned',
              'equals',
              true,
              'Women-owned business — confirm ownership criteria',
            ),
          ]
        : []),
      ...(id === 'startup'
        ? [
            rule(
              'stage',
              'in',
              ['Idea', 'Startup', 'Early stage'],
              'Early business stage',
            ),
          ]
        : []),
      ...(id === 'export'
        ? [rule('registrations', 'all', ['IEC'], 'Importer Exporter Code')]
        : []),
    ],
    documents: [
      'Udyam certificate',
      'PAN',
      'Bank details',
      'Financial statements',
      ...(id === 'machinery' ? ['Project report', 'Machinery quotation'] : []),
      ...(id === 'export' ? ['IEC certificate'] : []),
    ],
    process: [
      'Verify the current guidelines with the official administering authority.',
      'Prepare the required documents and review the checklist.',
      'Submit through the official portal when a verified application link is available.',
      'Record your application reference and follow up with the authority.',
    ],
    deadline: ['machinery', 'green', 'food', 'startup'].includes(id)
      ? '2026-12-31'
      : null,
    officialUrl: null,
    source: 'Illustrative seed record — no official government source',
    verifiedAt: null,
    status: 'Needs Review',
    demo: true,
    tags: [...goals.split(','), ...(id === 'green' ? ['solar subsidy'] : [])],
    createdAt: '2026-09-05T00:00:00.000Z',
  }),
);
